
#ifndef MMCW_CHROMALOC_ENUM
#define MMCW_CHROMALOC_ENUM(CLASS, NAME, NUMBER)
#endif

MMCW_CHROMALOC_ENUM(MMCW_CHROMALOC, UNSPECIFIED, 0) ///< Unspecified location
MMCW_CHROMALOC_ENUM(MMCW_CHROMALOC, LEFT, 1) ///< Left
MMCW_CHROMALOC_ENUM(MMCW_CHROMALOC, CENTER, 2) ///< Center
MMCW_CHROMALOC_ENUM(MMCW_CHROMALOC, TOPLEFT, 3) ///< Top left
MMCW_CHROMALOC_ENUM(MMCW_CHROMALOC, TOP, 4) ///< Top
MMCW_CHROMALOC_ENUM(MMCW_CHROMALOC, BOTTOMLEFT, 5) ///< Bottom left
MMCW_CHROMALOC_ENUM(MMCW_CHROMALOC, BOTTOM, 6) ///< Bottom