
#ifndef MMCW_COLRANGE_ENUM
#define MMCW_COLRANGE_ENUM(CLASS, NAME, NUMBER)
#endif

MMCW_COLRANGE_ENUM(MMCW_COLRANGE, UNSPECIFIED, 0) ///< No color range specified
MMCW_COLRANGE_ENUM(MMCW_COLRANGE, MPEG, 1)
MMCW_COLRANGE_ENUM(MMCW_COLRANGE, JPEG, 2)
