
#ifndef MMCW_COLSPC_ENUM
#define MMCW_COLSPC_ENUM(CLASS, NAME, NUMBER)
#endif

MMCW_COLSPC_ENUM(MMCW_COLSPC, RGB, 0) ///< Order of coefficients is actually GBR; also IEC 61966-2-1 (sRGB), YZX, and SMPTE ST 428-1
MMCW_COLSPC_ENUM(MMCW_COLSPC, BT709, 1) ///< ITU-R BT709; also ITU-R BT1361 / IEC 61966-2-4 xvYCC709 / derived in SMPTE RP 177 Annex B
MMCW_COLSPC_ENUM(MMCW_COLSPC, UNSPECIFIED, -1) ///< Unspecified color space
MMCW_COLSPC_ENUM(MMCW_COLSPC, RESERVED, 3) ///< Reserved for future use by ITU-T and ISO/IEC
MMCW_COLSPC_ENUM(MMCW_COLSPC, FCC, 4) ///< FCC Title 47 Code of Federal Regulations 73.682 (a)(20)
MMCW_COLSPC_ENUM(MMCW_COLSPC, BT470BG, 5) ///< ITU-R BT601-6 625 / ITU-R BT1358 625 / ITU-R BT1700 625 PAL & SECAM / IEC 61966-2-4 xvYCC601
MMCW_COLSPC_ENUM(MMCW_COLSPC, SMPTE170M, 6) ///< ITU-R BT601-6 525 / ITU-R BT1358 525 / ITU-R BT1700 NTSC / functionally identical to BT470BG
MMCW_COLSPC_ENUM(MMCW_COLSPC, SMPTE240M, 7) ///< Derived from SMPTE 170M primaries and D65 white point; 170M is derived from BT470 System M's primaries
MMCW_COLSPC_ENUM(MMCW_COLSPC, YCGCO, 8) ///< Used by Dirac / VC-2 and H.264 FRext; see ITU-T SG16
MMCW_COLSPC_ENUM(MMCW_COLSPC, YCOCG, 8) ///< Alias for YCGCO
MMCW_COLSPC_ENUM(MMCW_COLSPC, BT2020_NCL, 9) ///< ITU-R BT2020 non-constant luminance system
MMCW_COLSPC_ENUM(MMCW_COLSPC, BT2020_CL, 10) ///< ITU-R BT2020 constant luminance system
MMCW_COLSPC_ENUM(MMCW_COLSPC, SMPTE2085, 11) ///< SMPTE ST 2085, Y'D'zD'x
MMCW_COLSPC_ENUM(MMCW_COLSPC, CHROMA_DERIVED_NCL, 12) ///< Chromaticity-derived non-constant luminance system
MMCW_COLSPC_ENUM(MMCW_COLSPC, CHROMA_DERIVED_CL, 13) ///< Chromaticity-derived constant luminance system
MMCW_COLSPC_ENUM(MMCW_COLSPC, ICTCP, 14) ///< ITU-R BT.2100-0, ICtCp
