
#ifndef MMCW_PICTYPE_ENUM
#define MMCW_PICTYPE_ENUM(CLASS, NAME, NUMBER)
#endif

MMCW_PICTYPE_ENUM(MMCW_PICTYPE, NONE, 0) ///< No picture type specified
MMCW_PICTYPE_ENUM(MMCW_PICTYPE, I,  1)
MMCW_PICTYPE_ENUM(MMCW_PICTYPE, P,  2)
MMCW_PICTYPE_ENUM(MMCW_PICTYPE, B,  3)
MMCW_PICTYPE_ENUM(MMCW_PICTYPE, S,  4)
MMCW_PICTYPE_ENUM(MMCW_PICTYPE, SI, 5)
MMCW_PICTYPE_ENUM(MMCW_PICTYPE, SP, 6)
MMCW_PICTYPE_ENUM(MMCW_PICTYPE, BI, 7)
